apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote
  labels:
    app: vote
    tier: front
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: vote
          image: schoolofdevops/vote:v4
