apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
commonLabels:
  project: instavote
  env: staging
commonAnnotations:
  supported-by: "sre@example.com"
replicas:
  - name: vote
    count: 5
images:
  - name: schoolofdevops/vote
    newTag: v3
patches:
  - target:
      kind: Service
      name: vote
    patch: |-
      - op: replace
        path: /spec/ports/0/nodePort
        value: 30002
